### ISSUE TITLE
The security certificate expired 20.05.17.

### ISSUE THREAD

**Issue by ugg0t** [molefrog/chado#1]

**Comment by molefrog** [comment]
I use [Let's Encrypt](https://letsencrypt.org/) service in order to purchase new free certificates on the fly. I do not remember exactly how the whole schema works on the production server, but there should be a daemon/cron task that runs periodically and refreshes the certificate. 

Feels like the cron task just doesn't run. I used [this guide](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04), it might help (try looking at **step 4**).
